{{- if not .Values.config.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "greenops-agent.fullname" . }}
  labels:
    {{- include "greenops-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  carbon_api_key: {{ .Values.config.carbonApiKey | quote }}
{{- end }}