apiVersion: v1
kind: ConfigMap
metadata:
  name: greenops-agent-config
data:
  prometheus_url: "http://prometheus-server.monitoring.svc.cluster.local:9090"
  region: "DEFAULT"
  update_interval: "300"
---
apiVersion: v1
kind: Secret
metadata:
  name: greenops-agent-secret
type: Opaque
stringData:
  carbon_api_key: "replace-with-actual-key"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greenops-agent
  labels:
    app: greenops-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greenops-agent
  labels:
    app: greenops-agent
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets", "replicasets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greenops-agent
  labels:
    app: greenops-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: greenops-agent
subjects:
- kind: ServiceAccount
  name: greenops-agent
  namespace: default