apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenops-agent
  labels:
    app: greenops-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greenops-agent
  template:
    metadata:
      labels:
        app: greenops-agent
    spec:
      serviceAccountName: greenops-agent
      containers:
      - name: greenops-agent
        image: greenops-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PROMETHEUS_URL
          valueFrom:
            configMapKeyRef:
              name: greenops-agent-config
              key: prometheus_url
        - name: REGION
          valueFrom:
            configMapKeyRef:
              name: greenops-agent-config
              key: region
        - name: UPDATE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: greenops-agent-config
              key: update_interval
        - name: CARBON_API_KEY
          valueFrom:
            secretKeyRef:
              name: greenops-agent-secret
              key: carbon_api_key
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: greenops-agent
  labels:
    app: greenops-agent
spec:
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: greenops-agent
  type: ClusterIP